export interface Enrollment {
  id: string;
  student: {
    givenName: string;
    middleName?: string | null;
    familyName: string;
    suffix?: string | null;
    gender: string;
    dateOfBirth: Date;
    nationality: string;
    address?: string;
  };
  gradeLevel: string;
  section?: string | null;
  enrollmentDate: Date;
}

export const fetchEnrollments = (): Enrollment[] => {
  return [
    {
      id: "1024",
      student: {
        givenName: "Lily",
        familyName: "Anderson",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2018-05-12"),
        nationality: "Filipino",
        address: "123 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 1",
      section: "Einstein",
      enrollmentDate: new Date("2024-04-16"),
    },
    {
      id: "1025",
      student: {
        givenName: "Noah",
        familyName: "Brown",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2017-03-08"),
        nationality: "Filipino",
        address: "45 Rizal Ave, Manila, Philippines",
      },
      gradeLevel: "Grade 2",
      section: "Archimedes",
      enrollmentDate: new Date("2024-04-18"),
    },
    {
      id: "1026",
      student: {
        givenName: "Emma",
        familyName: "Carter",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2016-11-21"),
        nationality: "Filipino",
        address: "88 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 3",
      section: "Mendel",
      enrollmentDate: new Date("2024-04-22"),
    },
    {
      id: "1027",
      student: {
        givenName: "Liam",
        familyName: "Davis",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2015-07-30"),
        nationality: "Filipino",
        address: "12 Taft St, Pasig, Philippines",
      },
      gradeLevel: "Grade 4",
      section: "Pascal",
      enrollmentDate: new Date("2024-04-25"),
    },
    {
      id: "1028",
      student: {
        givenName: "Olivia",
        familyName: "Evans",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-02-15"),
        nationality: "Filipino",
        address: "77 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 5",
      section: null,
      enrollmentDate: new Date("2024-04-29"),
    },
    {
      id: "1029",
      student: {
        givenName: "Mason",
        familyName: "Foster",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-09-10"),
        nationality: "Filipino",
        address: "9 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-02"),
    },
    {
      id: "1030",
      student: {
        givenName: "Sophia",
        familyName: "Garcia",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2012-06-05"),
        nationality: "Filipino",
        address: "56 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 7",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-05"),
    },
    {
      id: "1031",
      student: {
        givenName: "Ethan",
        familyName: "Harris",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-12-20"),
        nationality: "Filipino",
        address: "34 España St, Manila, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-08"),
    },
    {
      id: "1032",
      student: {
        givenName: "Ava",
        familyName: "Irving",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2010-03-18"),
        nationality: "Filipino",
        address: "101 Banawe St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 9",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-10"),
    },
    {
      id: "1033",
      student: {
        givenName: "Lucas",
        familyName: "Johnson",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2009-08-25"),
        nationality: "Filipino",
        address: "77 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 10",
      section: null,
      enrollmentDate: new Date("2024-05-13"),
    },
    {
      id: "1034",
      student: {
        givenName: "Mia",
        familyName: "Kim",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2008-01-14"),
        nationality: "Filipino",
        address: "22 Ortigas Ave, Pasig, Philippines",
      },
      gradeLevel: "Grade 11",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-16"),
    },
    {
      id: "1035",
      student: {
        givenName: "Daniel",
        familyName: "Lopez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2007-11-09"),
        nationality: "Filipino",
        address: "88 Magallanes St, Makati, Philippines",
      },
      gradeLevel: "Grade 12",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-18"),
    },
    {
      id: "1036",
      student: {
        givenName: "Chloe",
        familyName: "Martinez",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2016-05-02"),
        nationality: "Filipino",
        address: "15 España St, Manila, Philippines",
      },
      gradeLevel: "Grade 3",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-21"),
    },
    {
      id: "1037",
      student: {
        givenName: "Benjamin",
        familyName: "Nguyen",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-07-07"),
        nationality: "Filipino",
        address: "34 Rizal Ave, Manila, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-24"),
    },
    {
      id: "1038",
      student: {
        givenName: "Harper",
        familyName: "O'Connor",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2017-09-16"),
        nationality: "Filipino",
        address: "56 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 2",
      section: null,
      enrollmentDate: new Date("2024-05-27"),
    },
    {
      id: "1039",
      student: {
        givenName: "Arjun",
        familyName: "Patel",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-05-28"),
        nationality: "Filipino",
        address: "77 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-30"),
    },
    {
      id: "1040",
      student: {
        givenName: "Zoe",
        familyName: "Quinn",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-02-02"),
        nationality: "Filipino",
        address: "22 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 5",
      section: "Archimedes",
      enrollmentDate: new Date("2024-06-02"),
    },
    {
      id: "1041",
      student: {
        givenName: "Mateo",
        familyName: "Reyes",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2010-12-20"),
        nationality: "Filipino",
        address: "12 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 9",
      section: "Mendel",
      enrollmentDate: new Date("2024-06-05"),
    },
    {
      id: "1042",
      student: {
        givenName: "Isabella",
        familyName: "Smith",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2008-09-18"),
        nationality: "Filipino",
        address: "101 Banawe St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 11",
      section: "Pascal",
      enrollmentDate: new Date("2024-06-10"),
    },
    {
      id: "1043",
      student: {
        givenName: "Jack",
        familyName: "Turner",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2012-01-22"),
        nationality: "Filipino",
        address: "34 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 7",
      section: null,
      enrollmentDate: new Date("2024-06-14"),
    },
    {
      id: "1044",
      student: {
        givenName: "Grace",
        familyName: "Upton",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2015-08-03"),
        nationality: "Filipino",
        address: "15 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 4",
      section: "Einstein",
      enrollmentDate: new Date("2024-04-17"),
    },
    {
      id: "1045",
      student: {
        givenName: "Diego",
        familyName: "Valdez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-11-09"),
        nationality: "Filipino",
        address: "88 Magallanes St, Makati, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Archimedes",
      enrollmentDate: new Date("2024-04-19"),
    },
  ];
};
