export interface Enrollment {
  id: string;
  student: {
    givenName: string;
    middleName?: string | null;
    familyName: string;
    suffix?: string | null;
    gender: string;
    dateOfBirth: Date;
    nationality: string;
    address?: string;
  };
  gradeLevel: string;
  section?: string | null;
  enrollmentDate: Date;
}

export const fetchEnrollments = (): Enrollment[] => {
  return [
    {
      id: "1024",
      student: {
        givenName: "Lily Jane",
        familyName: "Anderson",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2018-05-12"),
        nationality: "Filipino",
        address: "123 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 1",
      section: "Einstein",
      enrollmentDate: new Date("2024-04-16"),
    },
    {
      id: "1025",
      student: {
        givenName: "Noah",
        familyName: "Brown",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2017-03-08"),
        nationality: "Filipino",
        address: "45 Rizal Ave, Manila, Philippines",
      },
      gradeLevel: "Grade 2",
      section: "Archimedes",
      enrollmentDate: new Date("2024-04-18"),
    },
    {
      id: "1026",
      student: {
        givenName: "Emmanuela Niela",
        familyName: "Carter",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2016-11-21"),
        nationality: "Filipino",
        address: "88 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 3",
      section: "Mendel",
      enrollmentDate: new Date("2024-04-22"),
    },
    {
      id: "1027",
      student: {
        givenName: "Lialsea",
        familyName: "Davis",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2015-07-30"),
        nationality: "Filipino",
        address: "12 Taft St, Pasig, Philippines",
      },
      gradeLevel: "Grade 4",
      section: "Pascal",
      enrollmentDate: new Date("2024-04-25"),
    },
    {
      id: "1028",
      student: {
        givenName: "Xander Zeus",
        familyName: "Benitez",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-02-15"),
        nationality: "Filipino",
        address: "77 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 5",
      section: null,
      enrollmentDate: new Date("2024-04-29"),
    },
    {
      id: "1029",
      student: {
        givenName: "Mason Kim",
        familyName: "dela Cruz",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-09-10"),
        nationality: "Filipino",
        address: "9 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-02"),
    },
    {
      id: "1030",
      student: {
        givenName: "Sophia",
        familyName: "Garcia",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2012-06-05"),
        nationality: "Filipino",
        address: "56 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 7",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-05"),
    },
    {
      id: "1031",
      student: {
        givenName: "Ethan Markova",
        familyName: "Harris",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-12-20"),
        nationality: "Filipino",
        address: "34 España St, Manila, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-08"),
    },
    {
      id: "1032",
      student: {
        givenName: "Ava",
        familyName: "Irving",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2010-03-18"),
        nationality: "Filipino",
        address: "101 Banawe St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 9",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-10"),
    },
    {
      id: "1033",
      student: {
        givenName: "Lucas SKye",
        familyName: "Johnson",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2009-08-25"),
        nationality: "Filipino",
        address: "77 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 10",
      section: null,
      enrollmentDate: new Date("2024-05-13"),
    },
    {
      id: "1034",
      student: {
        givenName: "Mia Jane",
        familyName: "Kim",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2008-01-14"),
        nationality: "Filipino",
        address: "22 Ortigas Ave, Pasig, Philippines",
      },
      gradeLevel: "Grade 11",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-16"),
    },
    {
      id: "1035",
      student: {
        givenName: "Daniel",
        familyName: "Lopez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2007-11-09"),
        nationality: "Filipino",
        address: "88 Magallanes St, Makati, Philippines",
      },
      gradeLevel: "Grade 12",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-18"),
    },
    {
      id: "1036",
      student: {
        givenName: "Chloe Chaelle",
        familyName: "Martinez",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2016-05-02"),
        nationality: "Filipino",
        address: "15 España St, Manila, Philippines",
      },
      gradeLevel: "Grade 3",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-21"),
    },
    {
      id: "1037",
      student: {
        givenName: "Benjamin",
        familyName: "Nguyen",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-07-07"),
        nationality: "Filipino",
        address: "34 Rizal Ave, Manila, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-24"),
    },
    {
      id: "1038",
      student: {
        givenName: "Harper Flaundrey",
        familyName: "Macalasang",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2017-09-16"),
        nationality: "Filipino",
        address: "56 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 2",
      section: null,
      enrollmentDate: new Date("2024-05-27"),
    },
    {
      id: "1039",
      student: {
        givenName: "Arjun Jay",
        familyName: "Patel",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-05-28"),
        nationality: "Filipino",
        address: "77 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-30"),
    },
    {
      id: "1040",
      student: {
        givenName: "Zoey",
        familyName: "Quinn",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-02-02"),
        nationality: "Filipino",
        address: "22 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 5",
      section: "Archimedes",
      enrollmentDate: new Date("2024-06-02"),
    },
    {
      id: "1041",
      student: {
        givenName: "Mateo",
        familyName: "Reyes",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2010-12-20"),
        nationality: "Filipino",
        address: "12 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 9",
      section: "Mendel",
      enrollmentDate: new Date("2024-06-05"),
    },
    {
      id: "1042",
      student: {
        givenName: "Isabella Candela Janice Mae",
        familyName: "Aparagos",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2008-09-18"),
        nationality: "Filipino",
        address: "101 Banawe St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 11",
      section: "Pascal",
      enrollmentDate: new Date("2024-06-10"),
    },
    {
      id: "1043",
      student: {
        givenName: "Jack",
        familyName: "Turner",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2012-01-22"),
        nationality: "Filipino",
        address: "34 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 7",
      section: null,
      enrollmentDate: new Date("2024-06-14"),
    },
    {
      id: "1044",
      student: {
        givenName: "Grace",
        familyName: "Upton",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2015-08-03"),
        nationality: "Filipino",
        address: "15 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 4",
      section: "Einstein",
      enrollmentDate: new Date("2024-04-17"),
    },
    {
      id: "1045",
      student: {
        givenName: "Diego",
        familyName: "Valdez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-11-09"),
        nationality: "Filipino",
        address: "88 Magallanes St, Makati, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Archimedes",
      enrollmentDate: new Date("2024-04-19"),
    },
    {
      id: "1046",
      student: {
        givenName: "Hannah",
        familyName: "Walker",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2009-04-11"),
        nationality: "Filipino",
        address: "33 Quezon Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 10",
      section: "Mendel",
      enrollmentDate: new Date("2024-04-21"),
    },
    {
      id: "1047",
      student: {
        givenName: "Leo",
        familyName: "Xu",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-02-17"),
        nationality: "Filipino",
        address: "77 Legazpi St, Makati, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Pascal",
      enrollmentDate: new Date("2024-04-23"),
    },
    {
      id: "1048",
      student: {
        givenName: "Natalie",
        familyName: "Young",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2017-07-08"),
        nationality: "Filipino",
        address: "12 Aurora Blvd, Quezon City, Philippines",
      },
      gradeLevel: "Grade 2",
      section: null,
      enrollmentDate: new Date("2024-04-26"),
    },
    {
      id: "1049",
      student: {
        givenName: "Paul",
        familyName: "Zimmerman",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2007-05-30"),
        nationality: "Filipino",
        address: "88 España St, Manila, Philippines",
      },
      gradeLevel: "Grade 12",
      section: "Einstein",
      enrollmentDate: new Date("2024-04-28"),
    },
    {
      id: "1050",
      student: {
        givenName: "Brooke",
        familyName: "Adams",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-09-12"),
        nationality: "Filipino",
        address: "101 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 5",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-01"),
    },
    {
      id: "1051",
      student: {
        givenName: "Caleb",
        familyName: "Bennett",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2012-11-19"),
        nationality: "Filipino",
        address: "56 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 7",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-03"),
    },
    {
      id: "1052",
      student: {
        givenName: "Iris",
        familyName: "Coleman",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2010-03-24"),
        nationality: "Filipino",
        address: "22 Ortigas Ave, Pasig, Philippines",
      },
      gradeLevel: "Grade 9",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-04"),
    },
    {
      id: "1053",
      student: {
        givenName: "Marco",
        familyName: "Delgado",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2008-07-06"),
        nationality: "Filipino",
        address: "34 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 11",
      section: null,
      enrollmentDate: new Date("2024-05-06"),
    },

    {
      id: "1054",
      student: {
        givenName: "Ella",
        familyName: "Fleming",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2015-06-14"),
        nationality: "Filipino",
        address: "77 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 4",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-07"),
    },
    {
      id: "1055",
      student: {
        givenName: "Nathan",
        familyName: "Gomez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-10-21"),
        nationality: "Filipino",
        address: "45 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-08"),
    },
    {
      id: "1056",
      student: {
        givenName: "Luna",
        familyName: "Hughes",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2017-01-18"),
        nationality: "Filipino",
        address: "12 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 2",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-09"),
    },
    {
      id: "1057",
      student: {
        givenName: "Owen",
        familyName: "Ingram",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-09-25"),
        nationality: "Filipino",
        address: "88 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-10"),
    },
    {
      id: "1058",
      student: {
        givenName: "Aria Claire",
        familyName: "dela Peña",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2014-03-10"),
        nationality: "Filipino",
        address: "101 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 5",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-11"),
    },
    {
      id: "1059",
      student: {
        givenName: "Eli",
        familyName: "Khan",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2012-12-05"),
        nationality: "Filipino",
        address: "22 Ortigas Ave, Pasig, Philippines",
      },
      gradeLevel: "Grade 7",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-12"),
    },
    {
      id: "1060",
      student: {
        givenName: "Violet Dennis",
        familyName: "Lopez",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2010-06-23"),
        nationality: "Filipino",
        address: "34 EDSA Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 9",
      section: null,
      enrollmentDate: new Date("2024-05-13"),
    },
    {
      id: "1061",
      student: {
        givenName: "Leo",
        familyName: "Martinez",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2008-11-15"),
        nationality: "Filipino",
        address: "77 España Blvd, Manila, Philippines",
      },
      gradeLevel: "Grade 11",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-14"),
    },
    {
      id: "1062",
      student: {
        givenName: "Sofia",
        familyName: "Nguyen",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2016-07-02"),
        nationality: "Filipino",
        address: "45 Bonifacio St, Makati, Philippines",
      },
      gradeLevel: "Grade 3",
      section: "Mendel",
      enrollmentDate: new Date("2024-05-15"),
    },
    {
      id: "1063",
      student: {
        givenName: "Henry Luffy",
        familyName: "Ortiz",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2013-04-20"),
        nationality: "Filipino",
        address: "12 Katipunan Ave, Quezon City, Philippines",
      },
      gradeLevel: "Grade 6",
      section: "Pascal",
      enrollmentDate: new Date("2024-05-16"),
    },
    {
      id: "1064",
      student: {
        givenName: "Nora Mae",
        familyName: "Perez",
        middleName: null,
        suffix: null,
        gender: "F",
        dateOfBirth: new Date("2017-08-12"),
        nationality: "Filipino",
        address: "88 Mabini St, Quezon City, Philippines",
      },
      gradeLevel: "Grade 2",
      section: "Einstein",
      enrollmentDate: new Date("2024-05-17"),
    },
    {
      id: "1065",
      student: {
        givenName: "Samuel George",
        familyName: "Quinto",
        middleName: null,
        suffix: null,
        gender: "M",
        dateOfBirth: new Date("2011-02-14"),
        nationality: "Filipino",
        address: "101 Shaw Blvd, Mandaluyong, Philippines",
      },
      gradeLevel: "Grade 8",
      section: "Archimedes",
      enrollmentDate: new Date("2024-05-18"),
    },
  ];
};
