export interface Student {
  id: string;
  studentId: string;
  givenName: string;
  middleName: string | null;
  familyName: string;
  suffix: string | null;
  gender: string;
  dateOfBirth: Date;
  nationality: string;
  address: string | null;
}

export interface Guardian {
  name: string;
  relationship: string;
  contactNumber: string;
  emailAddress: string;
  addressSameAsStudent: boolean | null;
  address: string | null;
}

export const fetchStudents = async (): Promise<Student[]> => {
  return [
    {
      id: "d4f5a3c1-3e1b-4b8e-9f7c-0a1d2e3b4c5f",
      studentId: "1024",
      givenName: "Lily Jane",
      familyName: "Anderson",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2018-05-12"),
      nationality: "Filipino",
      address: "123 Mabini St, Quezon City, Philippines",
    },
    {
      id: "c7e8b9a2-5f1d-4a3c-8d6f-1b2c3e4f5a6b",
      studentId: "1025",
      givenName: "Noah",
      familyName: "Brown",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2017-03-08"),
      nationality: "Filipino",
      address: "45 Rizal Ave, Manila, Philippines",
    },
    {
      id: "e1d2c3b4-5a6f-4b7c-8d9e-2f3a4b5c6d7e",
      studentId: "1026",
      givenName: "Emmanuela Niela",
      familyName: "Carter",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2016-11-21"),
      nationality: "Filipino",
      address: "88 Bonifacio St, Makati, Philippines",
    },
    {
      id: "f3a4b5c6-7d8e-4f1a-9b2c-3e4f5a6b7c8d",
      studentId: "1027",
      givenName: "Lialsea",
      familyName: "Davis",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2015-07-30"),
      nationality: "Filipino",
      address: "12 Taft St, Pasig, Philippines",
    },
    {
      id: "a5b6c7d8-9e1f-4a2b-8c3d-4f5a6b7c8d9e",
      studentId: "1028",
      givenName: "Xander Zeus",
      familyName: "Benitez",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2014-02-15"),
      nationality: "Filipino",
      address: "77 Katipunan Ave, Quezon City, Philippines",
    },
    {
      id: "b6c7d8e9-1f2a-4b3c-9d4e-5f6a7b8c9d0e",
      studentId: "1029",
      givenName: "Mason Kim",
      familyName: "dela Cruz",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2013-09-10"),
      nationality: "Filipino",
      address: "9 España Blvd, Manila, Philippines",
    },
    {
      id: "c7d8e9f1-2a3b-4c5d-9e6f-7a8b9c0d1e2f",
      studentId: "1030",
      givenName: "Sophia",
      familyName: "Garcia",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2012-06-05"),
      nationality: "Filipino",
      address: "56 Shaw Blvd, Mandaluyong, Philippines",
    },
    {
      id: "d8e9f1a2-3b4c-5d6e-9f7a-8b9c0d1e2f3a",
      studentId: "1031",
      givenName: "Ethan Markova",
      familyName: "Harris",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2011-12-20"),
      nationality: "Filipino",
      address: "34 España St, Manila, Philippines",
    },
    {
      id: "e9f1a2b3-4c5d-6e7f-8a9b-0c1d2e3f4a5b",
      studentId: "1032",
      givenName: "Ava",
      familyName: "Irving",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2010-03-18"),
      nationality: "Filipino",
      address: "101 Banawe St, Quezon City, Philippines",
    },
    {
      id: "3a58cf1e-d70f-4292-82f3-0a5ba7a0f3ec",
      studentId: "1033",
      givenName: "Lucas SKye",
      familyName: "Johnson",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2009-08-25"),
      nationality: "Filipino",
      address: "77 EDSA Ave, Quezon City, Philippines",
    },
    {
      id: "8112ba3b-abbe-474a-8c13-492ef389e7ed",
      studentId: "1034",
      givenName: "Mia Jane",
      familyName: "Kim",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2008-01-14"),
      nationality: "Filipino",
      address: "22 Ortigas Ave, Pasig, Philippines",
    },
    {
      id: "26f603ac-36af-49b4-b223-727ff9a41ee6",
      studentId: "1035",
      givenName: "Daniel",
      familyName: "Lopez",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2007-11-09"),
      nationality: "Filipino",
      address: "88 Magallanes St, Makati, Philippines",
    },
    {
      id: "c4d5e6f7-8a9b-0c1d-2e3f-4a5b6c7d8e9f",
      studentId: "1036",
      givenName: "Chloe Chaelle",
      familyName: "Martinez",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2016-05-02"),
      nationality: "Filipino",
      address: "15 España St, Manila, Philippines",
    },
    {
      id: "d5e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a",
      studentId: "1037",
      givenName: "Benjamin",
      familyName: "Nguyen",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2013-07-07"),
      nationality: "Filipino",
      address: "34 Rizal Ave, Manila, Philippines",
    },
    {
      id: "e6f7a8b9-0c1d-2e3f-4a5b-6c7d8e9f0a1b",
      studentId: "1038",
      givenName: "Harper Flaundrey",
      familyName: "Macalasang",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2017-09-16"),
      nationality: "Filipino",
      address: "56 Mabini St, Quezon City, Philippines",
    },
    {
      id: "f7a8b9c0-1d2e-3f4a-5b6c-7d8e9f0a1b2c",
      studentId: "1039",
      givenName: "Arjun Jay",
      familyName: "Patel",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2011-05-28"),
      nationality: "Filipino",
      address: "77 Katipunan Ave, Quezon City, Philippines",
    },
    {
      id: "a8b9c0d1-2e3f-4a5b-6c7d-8e9f0a1b2c3d",
      studentId: "1040",
      givenName: "Zoey",
      familyName: "Quinn",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2014-02-02"),
      nationality: "Filipino",
      address: "22 Shaw Blvd, Mandaluyong, Philippines",
    },
    {
      id: "b9c0d1e2-3f4a-5b6c-7d8e-9f0a1b2c3d4e",
      studentId: "1041",
      givenName: "Mateo",
      familyName: "Reyes",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2010-12-20"),
      nationality: "Filipino",
      address: "12 España Blvd, Manila, Philippines",
    },
    {
      id: "c0d1e2f3-4a5b-6c7d-8e9f-0a1b2c3d4e5f",
      studentId: "1042",
      givenName: "Isabella Candela Janice Mae",
      familyName: "Aparagos",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2008-09-18"),
      nationality: "Filipino",
      address: "101 Banawe St, Quezon City, Philippines",
    },
    {
      id: "d1e2f3a4-5b6c-7d8e-9f0a-1b2c3d4e5f6a",
      studentId: "1043",
      givenName: "Jack",
      familyName: "Turner",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2012-01-22"),
      nationality: "Filipino",
      address: "34 EDSA Ave, Quezon City, Philippines",
    },
    {
      id: "e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b",
      studentId: "1044",
      givenName: "Grace",
      familyName: "Upton",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2015-08-03"),
      nationality: "Filipino",
      address: "15 Bonifacio St, Makati, Philippines",
    },
    {
      id: "f3a4b5c6-7d8e-9f0a-1b2c-3d4e5f6a7b8c",
      studentId: "1045",
      givenName: "Diego",
      familyName: "Valdez",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2013-11-09"),
      nationality: "Filipino",
      address: "88 Magallanes St, Makati, Philippines",
    },
    {
      id: "a4b5c6d7-8e9f-0a1b-2c3d-4e5f6a7b8c9d",
      studentId: "1046",
      givenName: "Hannah",
      familyName: "Walker",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2009-04-11"),
      nationality: "Filipino",
      address: "33 Quezon Ave, Quezon City, Philippines",
    },
    {
      id: "b5c6d7e8-9f0a-1b2c-3d4e-5f6a7b8c9d0e",
      studentId: "1047",
      givenName: "Leo",
      familyName: "Xu",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2011-02-17"),
      nationality: "Filipino",
      address: "77 Legazpi St, Makati, Philippines",
    },
    {
      id: "c6d7e8f9-0a1b-2c3d-4e5f-6a7b8c9d0e1f",
      studentId: "1048",
      givenName: "Natalie",
      familyName: "Young",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2017-07-08"),
      nationality: "Filipino",
      address: "12 Aurora Blvd, Quezon City, Philippines",
    },
    {
      id: "d7e8f9a0-1b2c-3d4e-5f6a-7b8c9d0e1f2a",
      studentId: "1049",
      givenName: "Paul",
      familyName: "Zimmerman",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2007-05-30"),
      nationality: "Filipino",
      address: "88 España St, Manila, Philippines",
    },
    {
      id: "e8f9a0b1-2c3d-4e5f-6a7b-8c9d0e1f2a3b",
      studentId: "1050",
      givenName: "Brooke",
      familyName: "Adams",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2014-09-12"),
      nationality: "Filipino",
      address: "101 Mabini St, Quezon City, Philippines",
    },
    {
      id: "f9a0b1c2-3d4e-5f6a-7b8c-9d0e1f2a3b4c",
      studentId: "1051",
      givenName: "Caleb",
      familyName: "Bennett",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2012-11-19"),
      nationality: "Filipino",
      address: "56 Shaw Blvd, Mandaluyong, Philippines",
    },
    {
      id: "a0b1c2d3-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
      studentId: "1052",
      givenName: "Iris",
      familyName: "Coleman",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2010-03-24"),
      nationality: "Filipino",
      address: "22 Ortigas Ave, Pasig, Philippines",
    },
    {
      id: "b1c2d3e4-5f6a-7b8c-9d0e-1f2a3b4c5d6e",
      studentId: "1053",
      givenName: "Marco",
      familyName: "Delgado",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2008-07-06"),
      nationality: "Filipino",
      address: "34 EDSA Ave, Quezon City, Philippines",
    },
    {
      id: "c2d3e4f5-6a7b-8c9d-0e1f-2a3b4c5d6e7f",
      studentId: "1054",
      givenName: "Ella",
      familyName: "Fleming",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2015-06-14"),
      nationality: "Filipino",
      address: "77 España Blvd, Manila, Philippines",
    },
    {
      id: "d3e4f5a6-7b8c-9d0e-1f2a-3b4c5d6e7f8a",
      studentId: "1055",
      givenName: "Nathan",
      familyName: "Gomez",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2013-10-21"),
      nationality: "Filipino",
      address: "45 Bonifacio St, Makati, Philippines",
    },
    {
      id: "e4f5a6b7-8c9d-0e1f-2a3b-4c5d6e7f8a9b",
      studentId: "1056",
      givenName: "Luna",
      familyName: "Hughes",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2009-12-09"),
      nationality: "Filipino",
      address: "101 Katipunan Ave, Quezon City, Philippines",
    },
    {
      id: "f5a6b7c8-9d0e-1f2a-3b4c-5d6e7f8a9b0c",
      studentId: "1057",
      givenName: "Owen",
      familyName: "Iglesias",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2011-08-29"),
      nationality: "Filipino",
      address: "12 Aurora Blvd, Quezon City, Philippines",
    },
    {
      id: "a6b7c8d9-0e1f-2a3b-4c5d-6e7f8a9b0c1d",
      studentId: "1058",
      givenName: "Stella",
      familyName: "Jackson",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2017-03-15"),
      nationality: "Filipino",
      address: "88 Magallanes St, Makati, Philippines",
    },
    {
      id: "b7c8d9e0-1f2a-3b4c-5d6e-7f8a9b0c1d2e",
      studentId: "1059",
      givenName: "Ryan",
      familyName: "Kim",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2007-06-23"),
      nationality: "Filipino",
      address: "34 Rizal Ave, Manila, Philippines",
    },
    {
      id: "c8d9e0f1-2a3b-4c5d-6e7f-8a9b0c1d2e3f",
      studentId: "1060",
      givenName: "Violet",
      familyName: "Lopez",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2014-01-11"),
      nationality: "Filipino",
      address: "22 EDSA Ave, Quezon City, Philippines",
    },
    {
      id: "d9e0f1a2-3b4c-5d6e-7f8a-9b0c1d2e3f4a",
      studentId: "1061",
      givenName: "Leo",
      familyName: "Martinez",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2012-09-19"),
      nationality: "Filipino",
      address: "77 Bonifacio St, Makati, Philippines",
    },
    {
      id: "e0f1a2b3-4c5d-6e7f-8a9b-0c1d2e3f4a5b",
      studentId: "1062",
      givenName: "Aria",
      familyName: "Nguyen",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2010-05-02"),
      nationality: "Filipino",
      address: "101 Katipunan Ave, Quezon City, Philippines",
    },
    {
      id: "f1a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c",
      studentId: "1063",
      givenName: "Eli",
      familyName: "Ocampo",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2008-03-17"),
      nationality: "Filipino",
      address: "12 Aurora Blvd, Quezon City, Philippines",
    },
    {
      id: "a2b3c4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7d",
      studentId: "1064",
      givenName: "Clara",
      familyName: "Perez",
      middleName: null,
      suffix: null,
      gender: "F",
      dateOfBirth: new Date("2015-10-05"),
      nationality: "Filipino",
      address: "45 Rizal Ave, Manila, Philippines",
    },
    {
      id: "b3c4d5e6-7f8a-9b0c-1d2e-3f4a5b6c7d8e",
      studentId: "1065",
      givenName: "Santiago",
      familyName: "Quizon",
      middleName: null,
      suffix: null,
      gender: "M",
      dateOfBirth: new Date("2013-12-22"),
      nationality: "Filipino",
      address: "56 Shaw Blvd, Mandaluyong, Philippines",
    },
  ];
};

export const fetchStudent = async (id: string): Promise<Student | null> => {
  const students = await fetchStudents();
  const targetStudent = students.find((student) => student.id === id);

  return targetStudent ?? null;
};

export const fetchStudentGuardians = (studentId: string): Guardian[] => {
  return studentId === "1234"
    ? [
        {
          name: "Jane Doe",
          relationship: "Mother",
          contactNumber: "09171234567",
          emailAddress: "jane.doe@example.com",
          addressSameAsStudent: true,
          address: null,
        },
        {
          name: "John Doe",
          relationship: "Father",
          contactNumber: "09171234568",
          emailAddress: "john.doe@example.com",
          addressSameAsStudent: null,
          address: "381, Other St, Cityville, Countryland",
        },
      ]
    : [];
};
